version: '2'

services:
  rest-nvd:
    build: .
    container_name: vulnerability-assessment-tool-rest-nvd
    hostname: rest-nvd
    ports:
      - "22222:80"
    environment:
      - CVE_DATA_PATH=/data
      - FEED_SCHEMA_VERSION=1.1
      - LOG_LEVEL=debug
      - WORKERS_PER_CORE=1
