version: '2'

services:
  frontend-apps:
    container_name: vulnerability-assessment-tool-frontend-apps
    hostname: frontend-apps
    image: vulas/vulnerability-assessment-tool-frontend-apps:${VULAS_RELEASE}
    expose:
      - "8080"
    security_opt:
      - no-new-privileges
    restart: always

  frontend-bugs:
    container_name: vulnerability-assessment-tool-frontend-bugs
    hostname: frontend-bugs
    image: vulas/vulnerability-assessment-tool-frontend-bugs:${VULAS_RELEASE}
    expose:
      - "8080"
    security_opt:
      - no-new-privileges
    restart: always

  haproxy:
    container_name: vulnerability-assessment-tool-haproxy
    hostname: haproxy
    env_file: .env
    image: haproxy:alpine
    ports:
      - "8033:8080"
      - "8034:7070"
    volumes:
      - "./haproxy/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
    depends_on:
      - frontend-apps
      - frontend-bugs
      - rest-backend
      - rest-lib-utils
      - rest-nvd
    security_opt:
      - no-new-privileges
    restart: always

  patch-lib-analyzer:
    container_name: vulnerability-assessment-tool-patch-lib-analyzer
    hostname: patch-lib-analyzer
    image: vulas/vulnerability-assessment-tool-patch-lib-analyzer:${VULAS_RELEASE}
    expose:
      - "8080"
    volumes:
      - "./data/patcheval:/patcheval-data"
    links:
      - rest-backend:backend
      - rest-lib-utils:cia
    depends_on: 
      - rest-backend
    environment:
      - PATCHEVAL_OPTS=-bug "" -folder /patcheval-data -j -h 0 -p 6
      - vulas.shared.cia.serviceUrl=http://cia:8092/cia
      - vulas.shared.backend.serviceUrl=http://backend:8091/backend
      - vulas.patchEval.onlyAddNewResults=true
    security_opt:
      - no-new-privileges
    restart: always
  
  postgresql:
    container_name: vulnerability-assessment-tool-postgresql
    hostname: postgresql
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=vulas
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "8032:5432"
    volumes:
      - vulnerability-assessment-tool-postgres-data:/var/lib/postgresql/data
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    security_opt:
      - no-new-privileges
    restart: always

  rest-backend:
    container_name: vulnerability-assessment-tool-rest-backend
    hostname: rest-backend
    env_file: 
      - .env
      - ./rest-backend/conf/restbackend.properties
    image: vulas/vulnerability-assessment-tool-rest-backend:${VULAS_RELEASE}
    expose:
      - "8091"
    environment:
      - DELAY_STARTUP=5
      - vulas.shared.cia.serviceUrl=http://cia:8092/cia
      - vulas.backend.coverageService.langConfidenceThreshold=0.2
      - vulas.backend.coverageService.licenseConfidenceThreshold=0.2
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
    links:
      - postgresql:postgresql
      - rest-lib-utils:cia
    volumes:
      - "./data/db-dump/flyway-callbacks:/flyway-callbacks"
    depends_on: 
      - postgresql
    security_opt:
      - no-new-privileges
    restart: always

  rest-lib-utils:
    container_name: vulnerability-assessment-tool-rest-lib-utils
    hostname: rest-lib-utils
    image: vulas/vulnerability-assessment-tool-rest-lib-utils:${VULAS_RELEASE}
    expose:
        - "8092"
    volumes:
      - "./data/rest-lib-utils:/root/"
    security_opt:
      - no-new-privileges
    restart: always

  rest-nvd:
    extends:
     file: ../rest-nvd/docker-compose.yml
     service: rest-nvd
    container_name: vulnerability-assessment-tool-rest-nvd
    hostname: rest-nvd
    image: vulas/vulnerability-assessment-tool-rest-nvd:${VULAS_RELEASE}
    expose:
      - "80"
    security_opt:
      - no-new-privileges
    restart: always

  cache:
    container_name: vulnerability-assessment-tool-cache
    hostname: cache
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./cache/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/cache/:/tmp/cache_all/
    security_opt:
      - no-new-privileges
    restart: always

volumes:
  vulnerability-assessment-tool-postgres-data:
